const ticketsdata = [
  {
    id: 1,
    from: "Moscow",
    to: "Berlin",
    company: "FlyDubai",
    price: 100,
    currency: "RUB",
    startTime: 1,
    endTime: 4,
    duration: 3,
    date: "22.11.24",
    connectionAmount: 1,
  },
  {
    id: 2,
    from: "Kazan",
    to: "Paris",
    company: "AirFrance",
    price: 200,
    currency: "RUB",
    startTime: 2,
    endTime: 2,
    duration: 4,
    date: "21.11.24",
    connectionAmount: 2,
  },
  {
    id: 3,
    from: "Tomsk",
    to: "Vladivostok",
    company: "Rossiya",
    price: 50,
    currency: "RUB",
    startTime: 1,
    endTime: 3,
    duration: 2,
    date: "20.11.24",
    connectionAmount: null,
  },
  {
    id: 4,
    from: "Moscow",
    to: "Berlin",
    company: "FlyDubai",
    price: 100,
    currency: "RUB",
    startTime: 1,
    endTime: 4,
    duration: 3,
    date: "22.11.24",
    connectionAmount: null,
  },
  {
    id: 1,
    from: "St.Petersburg",
    to: "Barcelona",
    company: "Iberia",
    price: 100,
    currency: "EUR",
    startTime: 5,
    endTime: 4,
    duration: 9,
    date: "25.11.24",
    connectionAmount: null,
  },
];

export { ticketsdata };
